language: c
compiler:
  - clang
  - gcc
install:
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libev-dev libpcre3-dev cdbs dh-autoreconf valgrind
  - ./autogen.sh
script:
  - ./configure && make && make check
  - sudo make install && sudo make uninstall
  - bash -c "cd tests && ./functional_test valgrind --error-exitcode=1"
  - dpkg-buildpackage && sudo dpkg -i ../sniproxy_0.1-1_`dpkg --print-architecture`.deb

